#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time
import zipfile
from pathlib import Path

import duckdb


ROOT = Path("/Users/harikeshshukla/mla")

# ---------------------------------------------------------------------
# EXISTING FINAL TEST INFERENCE — READ ONLY
# ---------------------------------------------------------------------
OLD = ROOT / "candidate_output_final_v6"

S1_TEST = ROOT / "processed_dataset/test/test_source1.parquet"

CAND_S2 = OLD / "test_candidates_s1_s2.parquet"
CAND_S3 = OLD / "test_candidates_s1_s3.parquet"

SCORED_S2 = OLD / "test_scored_s1_s2.parquet"
SCORED_S3 = OLD / "test_scored_s1_s3.parquet"

CAND_MANIFEST = OLD / "candidate_pairs_manifest.json"

# Existing exact candidate_pairs.tsv was generated from CAND_S2/CAND_S3.
EXISTING_CANDIDATE_TSV = ROOT / "student_resource/output/candidate_pairs.tsv"

VALIDATOR = ROOT / "student_resource/utils/validate_submission.py"
TEST_DIR = ROOT / "student_resource/dataset/test"

# ---------------------------------------------------------------------
# NEW FINALIZATION OUTPUT — ISOLATED
# ---------------------------------------------------------------------
OUT = ROOT / "candidate_output_final_v10_threshold"
OUT_OUTPUT = OUT / "output"
OUT_CODE = OUT / "code"
OUT_REPORT = OUT / "reports"
TMP = OUT / "tmp"

MATCHING_FINAL = OUT_OUTPUT / "matching_results.tsv"
CANDIDATE_FINAL = OUT_OUTPUT / "candidate_pairs.tsv"

# Frozen policy selected on the leakage-safe old validation experiment.
THRESHOLD = 20.945884704589844

MEMORY = os.environ.get("FINALIZE_MEMORY", "2GB")
THREADS = int(os.environ.get("FINALIZE_THREADS", "1"))

EXPECTED_TEST_S1 = 1_732_544
EXPECTED_CAND_S2 = 25_448_679
EXPECTED_CAND_S3 = 44_404_686


FEATURES = [
    "name_similarity",
    "address_similarity",
    "name_exact",
    "address_exact",
    "country_exact",
    "name_length_ratio",
    "address_length_ratio",
    "evidence_rows",
    "evidence_file_count",
    "exact_key_count",
    "base_score",
    "log_base_rank",
    "name_x_address",
    "name_minus_address",
    "similarity_mean",
    "similarity_min",
    "exact_field_count",
]


REQUIREMENTS = """duckdb==1.5.5
numpy==2.3.2
pandas==3.0.6
pyarrow==25.0.1
RapidFuzz==3.14.6
scikit-learn==1.9.1
scipy==1.18.1
joblib==1.6.0
cloudpickle==3.1.2
Unidecode==1.4.0
"""


README = r"""# Amazon ML Challenge 2026 — Auronix Final Pipeline

## Final production policy

The final production submission uses the already-built V6 + V9.1
candidate pool and V10 pairwise ranking model.

For each Source-1 record:

1. Score the complete candidate pool for Source 2 and Source 3.
2. Rank independently within each target source.
3. Keep only the rank-1 candidate from each target source.
4. Accept that rank-1 candidate only when:

       v10_utility >= 20.945884704589844

5. Otherwise emit no match for that target source.

This produces at most one S2 match and at most one S3 match per
Source-1 entity.

## Candidate generation

The final test candidate pools are the candidate sets generated by the
existing production baseline:

- V1 exact composite keys
- V2 postal blocking
- V4 selected address/postal blocks
- V5 structured name/postal and address/postal blocks
- V9.1 numeric-address + name-prefix blocking

The exact candidate Parquet pools used for inference are:

- test_candidates_s1_s2.parquet
- test_candidates_s1_s3.parquet

`candidate_pairs.tsv` is generated from those exact model-input pools.

## Model

Two separate pairwise LogisticRegression rankers are used:

- S1 -> S2
- S1 -> S3

The V10 feature set is:

name_similarity,
address_similarity,
name_exact,
address_exact,
country_exact,
name_length_ratio,
address_length_ratio,
evidence_rows,
evidence_file_count,
exact_key_count,
base_score,
log_base_rank,
name_x_address,
name_minus_address,
similarity_mean,
similarity_min,
exact_field_count

The vectors are standardized before LogisticRegression.

Training uses pairwise positive-vs-negative examples constructed from
the labelled training candidate pool.

## Base score

The transparent base score is:

30 * name_exact
+ 25 * address_exact
+ 8 * country_exact
+ 22 * name_similarity
+ 12 * address_similarity
+ 2 * name_length_ratio
+ 1 * address_length_ratio
+ 0.75 * evidence_file_count (clipped at 4)
+ 0.25 * exact_key_count (clipped at 5)

## Threshold selection

The threshold was selected on the old V7 validation split using a
model trained only on the non-validation Source-1 entities.

Baseline K1/K1:

macro F0.5 = 0.594111908498

Optimized Top-1 + abstention:

threshold = 20.945884704589844
macro F0.5 = 0.617515903939

The threshold was frozen before final test output generation.

The V8-expanded candidate architecture was separately audited. It
improved retrieval recall but reduced the precision-heavy validation
F0.5 under the audited prediction policy, so the final production
candidate pool remains the V6 + V9.1 pool.

The locked Final Holdout V2 was not used for threshold tuning.

## Data integrity

Only the supplied challenge data and internally derived features are
used. No external business identity lookup, external database,
geocoding API, or external business-data augmentation is used.

Country is treated as an open-set string label; no US/India-only
filtering is used.

## Required outputs

output/matching_results.tsv
output/candidate_pairs.tsv

Every Source-1 test entity appears exactly once in matching_results.tsv.

Empty matched_entity_ids represents abstention/no predicted match.

Every predicted ID comes from the final candidate set.
"""


METHODOLOGY = r"""# Amazon ML Challenge 2026 — Auronix Methodology

## 1. Methodology used

The task is treated as large-scale cross-source business entity
resolution. Source 1 is matched independently to Source 2 and Source 3.

The production pipeline uses deterministic candidate generation followed
by transparent feature extraction and learned pairwise ranking.

The challenge metric is macro F0.5 per Source-1 entity, including
singletons. The metric is precision-heavy, so incorrect merges are
especially costly.

## 2. Candidate generation / blocking

Candidate generation was developed iteratively using the supplied
training data.

The production candidate pool combines complementary blocking families:

- V1 exact normalized composite keys
- V2 postal blocking
- V4 selected address/postal structures
- V5 structured name/postal and address/postal blocks
- V9.1 numeric-address + name-prefix blocking

For final test inference the resulting exact candidate pools contain:

- S1 -> S2: 25,448,679 candidate pairs
- S1 -> S3: 44,404,686 candidate pairs

The candidate pool recorded in candidate_pairs.tsv is the exact candidate
set supplied to the inference ranking stage.

## 3. Feature engineering

For every candidate pair the pipeline computes:

- normalized name similarity
- normalized address similarity
- exact normalized name indicator
- exact normalized address indicator
- exact country indicator
- name length ratio
- address length ratio
- number of evidence rows
- number of distinct evidence groups
- exact-key count
- transparent base score
- logarithmic base-rank feature
- name/address interaction
- name/address difference
- mean similarity
- minimum similarity
- exact-field count

RapidFuzz is used for fuzzy name and address similarity.

## 4. Model architecture

Two independent pairwise LogisticRegression rankers are trained:

- S1 -> S2
- S1 -> S3

Training examples are constructed by comparing a positive candidate
against selected negative candidates within the same Source-1 entity.
The resulting difference features are standardized before fitting.

No external pretrained entity-resolution model is used.

## 5. Prediction policy

The model produces `v10_utility` for every candidate.

For each Source-1 entity and each target source:

- sort candidates by descending `v10_utility`;
- consider only rank 1;
- accept the rank-1 candidate only if
  `v10_utility >= 20.945884704589844`;
- otherwise emit no match for that target source.

Thus the final output can contain zero, one, or two predicted IDs
per Source-1 entity: at most one from Source 2 and one from Source 3.

## 6. Validation evidence

Using the old validation protocol with validation entities excluded
from model fitting:

Baseline K1/K1:

- macro F0.5 = 0.594111908498
- precision = 0.726289916951
- recall = 0.375394953889

Frozen Top-1 + abstention:

- threshold = 20.945884704589844
- macro F0.5 = 0.617515903939
- precision = 0.775931545288
- recall = 0.373745397252

The policy therefore trades a small amount of recall for substantially
higher precision, which is aligned with the challenge's F0.5 metric.

These are internal validation measurements, not hidden test-set scores.

## 7. V8 investigation

A four-block V8 expansion was evaluated separately:

- num_addr_name_prefix2
- addr_last2_postal
- name_last_token_postal
- name_first1_postal

The expansion increased retrieval Recall@20 in the audited validation
experiments, but under the precision-heavy F0.5 prediction audit its
K1/K1 and optimized threshold results remained below the corresponding
baseline policy.

Therefore the final test candidate pool remains the already-scored
V6 + V9.1 production pool.

## 8. Data integrity and fair play

The pipeline uses only the supplied challenge data and derived features.

No external business-identity lookup, commercial entity-resolution API,
government registry lookup, geocoding API, or external business-data
augmentation is used.

Country is handled as an open-set string field and is not restricted to
US/India.

## 9. Reproducibility

The submission package includes the final inference source, the final
thresholding logic, dependency versions, output files, and methodology.

The challenge-provided validator is executed before packaging.
"""


def header(title: str) -> None:
    print("\n" + "=" * 110)
    print(title)
    print("=" * 110, flush=True)


def qp(path: Path | str) -> str:
    return "'" + str(path).replace("'", "''") + "'"


def connect(tmp_dir: Path) -> duckdb.DuckDBPyConnection:
    tmp_dir.mkdir(parents=True, exist_ok=True)
    c = duckdb.connect()
    c.execute(f"PRAGMA memory_limit='{MEMORY}'")
    c.execute(f"PRAGMA threads={THREADS}")
    c.execute("PRAGMA preserve_insertion_order=false")
    c.execute(f"PRAGMA temp_directory={qp(tmp_dir)}")
    return c


def require(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Required file missing: {path}")


def count_rows(con, path: Path) -> int:
    return int(
        con.execute(
            f"SELECT COUNT(*) FROM read_parquet({qp(path)})"
        ).fetchone()[0]
    )


def schema(con, path: Path) -> list[str]:
    return [
        r[0]
        for r in con.execute(
            f"DESCRIBE SELECT * FROM read_parquet({qp(path)})"
        ).fetchall()
    ]


def preflight(con) -> dict:
    header("1. FINALIZATION PREFLIGHT")

    required = [
        S1_TEST,
        CAND_S2,
        CAND_S3,
        SCORED_S2,
        SCORED_S3,
        CAND_MANIFEST,
        EXISTING_CANDIDATE_TSV,
        VALIDATOR,
        TEST_DIR,
    ]

    for p in required:
        require(p)
        print(f"OK  {p}")

    s1_rows = int(
        con.execute(
            f"SELECT COUNT(*) FROM read_parquet({qp(S1_TEST)})"
        ).fetchone()[0]
    )
    c2_rows = count_rows(con, CAND_S2)
    c3_rows = count_rows(con, CAND_S3)
    sc2_rows = count_rows(con, SCORED_S2)
    sc3_rows = count_rows(con, SCORED_S3)

    print(f"\nTest S1 rows       : {s1_rows:,}")
    print(f"S2 candidate rows  : {c2_rows:,}")
    print(f"S3 candidate rows  : {c3_rows:,}")
    print(f"S2 scored rows      : {sc2_rows:,}")
    print(f"S3 scored rows      : {sc3_rows:,}")

    if s1_rows != EXPECTED_TEST_S1:
        raise RuntimeError(
            f"Unexpected S1 test row count: {s1_rows:,}"
        )

    if c2_rows != EXPECTED_CAND_S2:
        raise RuntimeError(
            f"Unexpected S2 candidate row count: {c2_rows:,}"
        )

    if c3_rows != EXPECTED_CAND_S3:
        raise RuntimeError(
            f"Unexpected S3 candidate row count: {c3_rows:,}"
        )

    if sc2_rows != c2_rows:
        raise RuntimeError(
            "S2 scored rows != S2 candidate rows"
        )

    if sc3_rows != c3_rows:
        raise RuntimeError(
            "S3 scored rows != S3 candidate rows"
        )

    required_scored = {
        "source1_entity_id",
        "candidate_entity_id",
        "v10_utility",
        "v10_rank",
    }

    for p in (SCORED_S2, SCORED_S3):
        cols = set(schema(con, p))
        missing = required_scored - cols
        if missing:
            raise RuntimeError(
                f"{p.name} missing required columns: {sorted(missing)}"
            )

    manifest = json.loads(
        CAND_MANIFEST.read_text(encoding="utf-8")
    )

    print("\nCandidate-pair manifest:")
    print(json.dumps(manifest, indent=2)[:4000])

    print("\nPREFLIGHT PASS")

    return {
        "test_s1_rows": s1_rows,
        "candidate_s2_rows": c2_rows,
        "candidate_s3_rows": c3_rows,
        "scored_s2_rows": sc2_rows,
        "scored_s3_rows": sc3_rows,
    }


def build_thresholded_rank(con, target: str) -> Path:
    scored = SCORED_S2 if target == "S2" else SCORED_S3

    out = OUT_OUTPUT / f"thresholded_top1_s1_{target.lower()}.parquet"
    out.unlink(missing_ok=True)

    con.execute(
        f"""
        COPY (
            SELECT
                source1_entity_id,
                candidate_entity_id,
                v10_utility,
                v10_rank
            FROM read_parquet({qp(scored)})
            WHERE v10_rank = 1
              AND v10_utility >= {THRESHOLD}
        )
        TO {qp(out)}
        (FORMAT PARQUET, COMPRESSION ZSTD)
        """
    )

    rows = count_rows(con, out)

    header(f"{target} FROZEN THRESHOLD OUTPUT")
    print(f"Threshold : {THRESHOLD:.15f}")
    print(f"Rows      : {rows:,}")
    print(f"Output    : {out}")

    return out


def build_matching_results(con, top_s2: Path, top_s3: Path) -> dict:
    header("2. BUILD FINAL matching_results.tsv")

    OUT_OUTPUT.mkdir(parents=True, exist_ok=True)

    con.execute(
        f"""
        COPY (
            WITH
            s2 AS (
                SELECT
                    source1_entity_id,
                    candidate_entity_id
                FROM read_parquet({qp(top_s2)})
            ),
            s3 AS (
                SELECT
                    source1_entity_id,
                    candidate_entity_id
                FROM read_parquet({qp(top_s3)})
            )
            SELECT
                t.entity_id AS source1_entity_id,
                CASE
                    WHEN s2.candidate_entity_id IS NOT NULL
                     AND s3.candidate_entity_id IS NOT NULL
                    THEN s2.candidate_entity_id || ',' || s3.candidate_entity_id

                    WHEN s2.candidate_entity_id IS NOT NULL
                    THEN s2.candidate_entity_id

                    WHEN s3.candidate_entity_id IS NOT NULL
                    THEN s3.candidate_entity_id

                    ELSE NULL
                END AS matched_entity_ids
            FROM read_parquet({qp(S1_TEST)}) t
            LEFT JOIN s2
                ON s2.source1_entity_id = t.entity_id
            LEFT JOIN s3
                ON s3.source1_entity_id = t.entity_id
            ORDER BY t.entity_id
        )
        TO {qp(MATCHING_FINAL)}
        (HEADER, DELIMITER '\\t')
        """
    )

    rows = int(
        con.execute(
            f"""
            SELECT COUNT(*)
            FROM read_csv(
                {qp(MATCHING_FINAL)},
                delim='\\t',
                header=true,
                columns={{
                    'source1_entity_id':'VARCHAR',
                    'matched_entity_ids':'VARCHAR'
                }}
            )
            """
        ).fetchone()[0]
    )

    nonempty = int(
        con.execute(
            f"""
            SELECT COUNT(*)
            FROM read_csv(
                {qp(MATCHING_FINAL)},
                delim='\\t',
                header=true,
                columns={{
                    'source1_entity_id':'VARCHAR',
                    'matched_entity_ids':'VARCHAR'
                }}
            )
            WHERE matched_entity_ids <> ''
            """
        ).fetchone()[0]
    )

    empty = rows - nonempty

    s2_selected = count_rows(con, top_s2)
    s3_selected = count_rows(con, top_s3)

    print(f"Rows                : {rows:,}")
    print(f"Non-empty S1        : {nonempty:,}")
    print(f"Empty S1            : {empty:,}")
    print(f"Accepted S2 top1    : {s2_selected:,}")
    print(f"Accepted S3 top1    : {s3_selected:,}")
    print(f"Output              : {MATCHING_FINAL}")

    if rows != EXPECTED_TEST_S1:
        raise RuntimeError(
            f"matching_results.tsv rows={rows:,}; "
            f"expected {EXPECTED_TEST_S1:,}"
        )

    return {
        "matching_rows": rows,
        "nonempty_source1": nonempty,
        "empty_source1": empty,
        "accepted_s2": s2_selected,
        "accepted_s3": s3_selected,
    }


def verify_existing_candidate_pairs(con) -> dict:
    header("3. VERIFY EXISTING EXACT candidate_pairs.tsv")

    require(EXISTING_CANDIDATE_TSV)

    rows = int(
        con.execute(
            f"""
            SELECT COUNT(*)
            FROM read_csv(
                {qp(EXISTING_CANDIDATE_TSV)},
                delim='\\t',
                header=true,
                columns={{
                    'source1_entity_id':'VARCHAR',
                    'candidate_entity_ids':'VARCHAR'
                }}
            )
            """
        ).fetchone()[0]
    )

    cols = con.execute(
        f"""
        SELECT *
        FROM read_csv(
            {qp(EXISTING_CANDIDATE_TSV)},
            delim='\\t',
            header=true,
            columns={{
                'source1_entity_id':'VARCHAR',
                'candidate_entity_ids':'VARCHAR'
            }}
        )
        LIMIT 1
        """
    ).description

    if rows != EXPECTED_TEST_S1:
        raise RuntimeError(
            f"candidate_pairs.tsv has {rows:,} rows; "
            f"expected {EXPECTED_TEST_S1:,}"
        )

    header_line = EXISTING_CANDIDATE_TSV.read_text(
        encoding="utf-8",
        errors="strict",
    ).splitlines()[0]

    if header_line != "source1_entity_id\tcandidate_entity_ids":
        raise RuntimeError(
            f"Unexpected candidate_pairs.tsv header: {header_line!r}"
        )

    # Copy byte-for-byte so the exact previously-built model-input
    # candidate set is retained.
    OUT_OUTPUT.mkdir(parents=True, exist_ok=True)
    shutil.copy2(EXISTING_CANDIDATE_TSV, CANDIDATE_FINAL)

    print(f"Rows       : {rows:,}")
    print(f"Header     : {header_line}")
    print(f"Copied to  : {CANDIDATE_FINAL}")

    return {"candidate_pairs_rows": rows}


def run_validator(matching: Path, candidate: Path) -> None:
    header("4. OFFICIAL CHALLENGE VALIDATOR")

    cmd = [
        sys.executable,
        str(VALIDATOR),
        "--matching",
        str(matching),
        "--candidate",
        str(candidate),
        "--test-dir",
        str(TEST_DIR),
        "--check-ids",
    ]

    print("Running:")
    print(" ".join(cmd))
    print()

    subprocess.run(cmd, check=True)

    print("\nOFFICIAL VALIDATOR PASS")


def publish_to_live_output() -> None:
    header("5. PUBLISH TO student_resource/output")

    LIVE_OUT = ROOT / "student_resource/output"
    LIVE_OUT.mkdir(parents=True, exist_ok=True)

    live_matching = LIVE_OUT / "matching_results.tsv"
    live_candidate = LIVE_OUT / "candidate_pairs.tsv"

    # candidate_pairs should be identical to the already verified exact pool.
    # We replace only after the complete new package has passed validation.
    backup_dir = OUT / "previous_live_output_backup"
    backup_dir.mkdir(parents=True, exist_ok=True)

    for p in (live_matching, live_candidate):
        if p.exists():
            shutil.move(
                str(p),
                str(backup_dir / p.name),
            )

    shutil.copy2(MATCHING_FINAL, live_matching)
    shutil.copy2(CANDIDATE_FINAL, live_candidate)

    print(f"Published matching  : {live_matching}")
    print(f"Published candidates: {live_candidate}")
    print(f"Previous live files : {backup_dir}")


def build_package(meta: dict) -> Path:
    header("6. BUILD FINAL AURONIX SUBMISSION PACKAGE")

    stage = OUT / "Auronix_submission_build"
    zip_path = ROOT / "Auronix_submission_v10_threshold.zip"

    if stage.exists():
        shutil.rmtree(stage)

    stage.mkdir(parents=True, exist_ok=True)
    (stage / "output").mkdir(parents=True, exist_ok=True)

    # Required outputs.
    shutil.copy2(
        MATCHING_FINAL,
        stage / "output/matching_results.tsv",
    )
    shutil.copy2(
        CANDIDATE_FINAL,
        stage / "output/candidate_pairs.tsv",
    )

    # Production source tree.
    src = stage / "code/business_entity_resolution/src"
    src.mkdir(parents=True, exist_ok=True)

    finalization_script = ROOT / "amazon_ml_finalize_v10_threshold.py"

    sources = [
        ROOT / "process_dataset.py",

        # Candidate-generation / scoring lineage used by the
        # production V6 + V9.1 candidate architecture.
        ROOT / "candidate_generation.py",
        ROOT / "candidate_generation_v2.py",
        ROOT / "candidate_generation_v2_safe.py",
        ROOT / "candidate_generation_v3.py",
        ROOT / "candidate_generation_v4.py",
        ROOT / "candidate_generation_v5.py",
        ROOT / "candidate_generation_v9_1.py",
        ROOT / "candidate_scoring_v6.py",
        ROOT / "candidate_scoring_v7.py",
        ROOT / "candidate_scoring_v8.py",

        # V10 model construction.
        ROOT / "amazon_ml_pipeline_v10_fixed.py",

        # Final test inference.
        ROOT / "amazon_ml_final_one_shot_v6.py",

        # Exact candidate_pairs construction.
        ROOT / "amazon_ml_make_candidate_pairs.py",

        # Frozen final Top-1 + abstention policy.
        finalization_script,

        # Official challenge validator.
        VALIDATOR,
    ]

    for p in sources:
        if p.exists():
            shutil.copy2(p, src / p.name)

    (stage / "code/business_entity_resolution/README.md").write_text(
        README,
        encoding="utf-8",
    )

    (stage / "code/business_entity_resolution/requirements.txt").write_text(
        REQUIREMENTS,
        encoding="utf-8",
    )

    (stage / "Documentation_template.md").write_text(
        METHODOLOGY,
        encoding="utf-8",
    )

    # Final model metadata, when available.
    coeff = OLD / "final_model_coefficients.json"
    if coeff.exists():
        shutil.copy2(
            coeff,
            stage / "code/business_entity_resolution/final_model_coefficients.json",
        )

    manifest = {
        "team_name": "Auronix",
        "version": "FINAL_V10_THRESHOLD",
        "threshold": THRESHOLD,
        "threshold_basis": "old_v7_validation_incremental_exact_top1_sweep",
        "matching_rows": meta["matching_rows"],
        "candidate_pairs_rows": meta["candidate_pairs_rows"],
        "accepted_s2": meta["accepted_s2"],
        "accepted_s3": meta["accepted_s3"],
        "empty_source1": meta["empty_source1"],
        "test_candidates_s2": EXPECTED_CAND_S2,
        "test_candidates_s3": EXPECTED_CAND_S3,
        "prospective_holdout_read_during_finalization": False,
        "test_ground_truth_used": False,
        "external_lookup_used": False,
        "final_holdout_tuned": False,
        "validator": "PASS",
        "model_features": FEATURES,
        "candidate_source": {
            "s2": str(CAND_S2),
            "s3": str(CAND_S3),
        },
        "scored_source": {
            "s2": str(SCORED_S2),
            "s3": str(SCORED_S3),
        },
    }

    (stage / "submission_manifest.json").write_text(
        json.dumps(manifest, indent=2),
        encoding="utf-8",
    )

    # Also save project-local manifest.
    (OUT / "final_manifest.json").write_text(
        json.dumps(manifest, indent=2),
        encoding="utf-8",
    )

    if zip_path.exists():
        zip_path.unlink()

    with zipfile.ZipFile(
        zip_path,
        "w",
        compression=zipfile.ZIP_DEFLATED,
        compresslevel=6,
    ) as z:
        for p in sorted(stage.rglob("*")):
            if p.is_file():
                z.write(
                    p,
                    p.relative_to(stage),
                )

    print(f"ZIP created: {zip_path}")
    print(f"ZIP size   : {zip_path.stat().st_size / (1024**2):.1f} MB")

    return zip_path


def main() -> None:
    started = time.time()

    header("AMAZON ML CHALLENGE 2026 — FINAL V10 THRESHOLD FINALIZATION")

    print(f"Project   : {ROOT}")
    print(f"Policy    : Top1 + abstention")
    print(f"Threshold : {THRESHOLD:.15f}")
    print(f"Memory    : {MEMORY}")
    print(f"Threads   : {THREADS}")
    print("V8 rerun  : NO")
    print("V10 rescore: NO")
    print("Test GT   : NO")
    print("Holdout tuning: NO")

    # New isolated output only.
    OUT.mkdir(parents=True, exist_ok=True)
    OUT_OUTPUT.mkdir(parents=True, exist_ok=True)
    OUT_REPORT.mkdir(parents=True, exist_ok=True)

    con = connect(TMP)

    try:
        meta = preflight(con)

        top_s2 = build_thresholded_rank(con, "S2")
        top_s3 = build_thresholded_rank(con, "S3")

        match_meta = build_matching_results(
            con,
            top_s2,
            top_s3,
        )

        cand_meta = verify_existing_candidate_pairs(con)

        run_validator(
            MATCHING_FINAL,
            CANDIDATE_FINAL,
        )

        combined_meta = {}
        combined_meta.update(meta)
        combined_meta.update(match_meta)
        combined_meta.update(cand_meta)
        combined_meta.update(
            {
                "threshold": THRESHOLD,
                "policy": "top1_per_target_plus_abstention",
                "runtime_seconds": None,
            }
        )

    finally:
        con.close()

    # Publish only after everything above succeeded.
    publish_to_live_output()

    zip_path = build_package(combined_meta)

    combined_meta["runtime_seconds"] = round(
        time.time() - started,
        3,
    )

    (OUT / "finalization_report.json").write_text(
        json.dumps(combined_meta, indent=2),
        encoding="utf-8",
    )

    header("✅ FINALIZATION COMPLETE")

    print(json.dumps(combined_meta, indent=2))
    print()
    print(f"Final output dir : {OUT}")
    print(f"matching_results : {MATCHING_FINAL}")
    print(f"candidate_pairs  : {CANDIDATE_FINAL}")
    print(f"Final ZIP        : {zip_path}")
    print()
    print("OLD V6 OUTPUTS PRESERVED.")
    print("FINAL HOLDOUT NOT USED FOR TUNING.")
    print("TEST GROUND TRUTH NOT USED.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted by user.", file=sys.stderr)
        raise
    except Exception as exc:
        print(
            f"\nFINALIZATION FAILED: {type(exc).__name__}: {exc}",
            file=sys.stderr,
        )
        raise
